### ISSUE TITLE
HTML Validation Errors

### ISSUE THREAD

**Issue by neilmispelaar** [imd1005-web-development-winter-2023/assignment-02-TSallamCode#2]
Hi @TSallamCode 

Really cool submission in flight for Assignment 02 🎉! 

Well done!

## Issue Description

I ran your code through the HTML Validator and there are a couple of errors being thrown.

Don't worry about the `warnings` or `info` items, just try to get at the errors listed. 

These issues might not address your images not appearing issue, but they could be contributing to other issues. 

## HTML Validator Results

Here is the link to the full results:

https://validator.w3.org/nu/?doc=https%3A%2F%2Fimd1005-web-development-winter-2023.github.io%2Fassignment-02-TSallamCode%2F

Screenshot

<img width="1398" alt="Screenshot 2023-02-25 at 9 42 28 AM" src="https://user-images.githubusercontent.com/9325038/221362986-bb77d1c2-f4a3-4446-8963-04953554de02.png">

**Comment by TSallamCode** [comment]
Thanks! Fixed HTML validation errors
