### ISSUE TITLE
CSS Validation Issues

### ISSUE THREAD

**Issue by neilmispelaar** [imd1005-web-development-winter-2023/assignment-02-TSallamCode#3]
Hi @TSallamCode 

## Issue Description

I ran your code through the CSS Validator and there are a couple of errors being thrown.

These items aren't likely causing your images issue, but they could be contributing to, or causing other issues.  

## CSS Validator Results

Here is the link to the full results:

https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fimd1005-web-development-winter-2023.github.io%2Fassignment-02-TSallamCode%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en

## Screenshot

<img width="1398" alt="Screenshot 2023-02-25 at 9 44 26 AM" src="https://user-images.githubusercontent.com/9325038/221363104-de335a04-4528-44b8-974d-19cc12b82d3a.png">

**Comment by TSallamCode** [comment]
Thanks! All fixed CSS validation
