### ISSUE TITLE
Broken links on images

### ISSUE THREAD

**Issue by neilmispelaar** [imd1005-web-development-winter-2023/assignment-02-TSallamCode#4]
Hi @TSallamCode 

## Issue description

Images not showing up because the links to the images are "broken". 

## Resolution 

Images references are case sensitive, and your code is referencing `aboutme.jpg` but the actual image in GitHub is `aboutme.JPG`. 

Would recommend keeping all of your images, files, assets, everything as completely lowercase. 

### Browser inspector editor where image set to matching file name 

<img width="1398" alt="Screenshot 2023-02-25 at 9 52 09 AM" src="https://user-images.githubusercontent.com/9325038/221363717-f699f77f-cdae-4352-83e5-b5e7f5d94a73.png">

### Browser inspector network tab showing which files are throwing not found errors 

<img width="1398" alt="Screenshot 2023-02-25 at 9 48 02 AM" src="https://user-images.githubusercontent.com/9325038/221363721-e9aa4396-84bd-4635-bb3e-1f0122c9d8f3.png">

**Comment by TSallamCode** [comment]
turns out I had a '/' before the directory. Thanks for this! Really appreciate it!
